### PR TITLE
adding poll to make sure reconcile doesn't error out if the resource is already present

### PR DESCRIPTION
**Pull request by JaydipGabani**

### CODE REVIEW

**Comment by shawn-hurley** [comment]
@JaydipGabani we will want to run this change in a sandbox test, can you report the results here.

**Comment by cooktheryan** [comment]
:+1: Let me know if you need me to populate a test image for you at all to use in sandbox

**Comment by cooktheryan** [comment]
Things appear very clean

```
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214
2022-02-14T18:55:27.948Z	INFO	controller-runtime.manager.controller.export	Export resource not found. Ignoring since object must be deleted	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:55:27.953Z	INFO	controller-runtime.manager.controller.export	Export resource not found. Ignoring since object must be deleted	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:55:28.113Z	INFO	controller-runtime.manager.controller.export	Creating a new Job	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate", "Job.Namespace": "validate", "Job.Name": "primer-export-primer"}
2022-02-14T18:55:29.153Z	INFO	controller-runtime.manager.controller.export	Creating a new Service Account	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate", "serviceAcct.Namespace": "validate", "serviceAcct.Name": "primer-export-primer"}
2022-02-14T18:55:30.163Z	INFO	controller-runtime.manager.controller.export	Creating a new oauth Secret	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate", "proxySecret.Namespace": "validate", "proxySecret.Name": "primer-export-primer"}
2022-02-14T18:55:31.174Z	INFO	controller-runtime.manager.controller.export	Creating a new PVC	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate", "persistentVC.Namespace": "validate", "persistentVC.Name": "primer-export-primer"}
2022-02-14T18:55:32.186Z	INFO	controller-runtime.manager.controller.export	Creating a new Route	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate", "appRoute.Namespace": "validate", "appRoute.Name": "primer-export-primer"}
2022-02-14T18:55:33.253Z	INFO	controller-runtime.manager.controller.export	Creating a new Cluster Role	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate", "clusterRole.Namespace": "", "clusterRole.Name": "primer-export-validate-primer"}
2022-02-14T18:55:34.321Z	INFO	controller-runtime.manager.controller.export	Creating a new Cluster Role Binding	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate", "clusterRoleBinding.Namespace": "", "clusterRoleBinding.Name": "primer-export-validate-primer"}
2022-02-14T18:55:35.383Z	INFO	controller-runtime.manager.controller.export	Creating a new Network Policy{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate", "netPol.Namespace": "validate", "netPol.Name": "primer-export-primer"}
2022-02-14T18:55:36.398Z	INFO	controller-runtime.manager.controller.export	Creating a new Service	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate", "service.Namespace": "validate", "service.Name": "primer-export-primer"}
2022-02-14T18:55:37.418Z	INFO	controller-runtime.manager.controller.export	Deployment is not ready	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:55:37.678Z	INFO	controller-runtime.manager.controller.export	Deployment is not ready	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:55:38.206Z	INFO	controller-runtime.manager.controller.export	Deployment is not ready	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:55:38.208Z	INFO	controller-runtime.manager.controller.export	Deployment is not ready	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:55:38.212Z	INFO	controller-runtime.manager.controller.export	Deployment is not ready	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:55:40.095Z	INFO	controller-runtime.manager.controller.export	Deployment is not ready	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:55:40.104Z	INFO	controller-runtime.manager.controller.export	Deployment is not ready	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:56:12.490Z	INFO	controller-runtime.manager.controller.export	Cleaning up clusterrole	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:56:12.499Z	INFO	controller-runtime.manager.controller.export	cleaning clusterrolebinding	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:56:12.510Z	INFO	controller-runtime.manager.controller.export	job cleanup	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:56:12.524Z	INFO	controller-runtime.manager.controller.export	Items extracted successfully{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:56:12.535Z	INFO	controller-runtime.manager.controller.export	Serving up Export Download	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:56:12.535Z	INFO	controller-runtime.manager.controller.export	Creating a new Deployment	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate", "deployment.Namespace": "validate", "deployment.Name": "primer-export-primer"}
2022-02-14T18:56:13.585Z	INFO	controller-runtime.manager.controller.export	Items extracted successfully{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:56:13.593Z	INFO	controller-runtime.manager.controller.export	Serving up Export Download	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:56:13.593Z	INFO	controller-runtime.manager.controller.export	Deployment is not ready	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:56:13.593Z	INFO	controller-runtime.manager.controller.export	Items extracted successfully{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:56:13.601Z	INFO	controller-runtime.manager.controller.export	Serving up Export Download	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:56:13.601Z	INFO	controller-runtime.manager.controller.export	Deployment is not ready	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:56:16.513Z	INFO	controller-runtime.manager.controller.export	Items extracted successfully{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:56:16.522Z	INFO	controller-runtime.manager.controller.export	Serving up Export Download	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:56:16.522Z	INFO	controller-runtime.manager.controller.export	Items extracted successfully{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:56:16.540Z	INFO	controller-runtime.manager.controller.export	Items extracted successfully{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:56:16.551Z	INFO	controller-runtime.manager.controller.export	Serving up Export Download	{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
2022-02-14T18:56:16.551Z	INFO	controller-runtime.manager.controller.export	Items extracted successfully{"reconciler group": "primer.gitops.io", "reconciler kind": "Export", "name": "primer", "namespace": "validate"}
```

**Review by shawn-hurley — APPROVED** [review]

**Pull request merged**
