### PR TITLE
Csv patch

### PR DESCRIPTION
**Pull request by cooktheryan**
Patch of the csv so for future releases someone can just run make bundle and the csv will generate all required fields

### CODE REVIEW

**Comment by cooktheryan** [comment]
Putting in this PR based on some of the items I saw while you were doing the community operator review

**Comment by rayfordj** [comment]
@cooktheryan , seems reasonable to me.  Let's take the opportunity with this PR to add at least one category from [categories](https://github.com/operator-framework/community-operators/blob/master/categories.json) to the CSV in konveyor/gitops-primer repo to satisfy @jmontleon's [community-operators-prod/pull/231](https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/231) comment for a category.  Do any of those in the categories list seem appropriate?

Example from Crane's [1.5.1 CSV](https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/211/files#diff-10cf8e0c080c357e9aef2cc92ecd5be514775478b423d0ad3bece4bd98f6ef59R7-R12) 
```
  annotations:
    # <...snip...>
    description: Facilitates migration of container workloads from OpenShift 3.x to OpenShift 4.x
    categories: 'OpenShift Optional'
```

Thanks!

**Comment by rayfordj** [comment]
Apparently, I'm not able to comment directly against it since it's not part of the changes...

For `description:` on [gitops-primer.clusterserviceversion.yaml#L32](https://github.com/konveyor/gitops-primer/blob/5d7469deba922e674f4c5af8264a0ec0c7a4daec/bundle/manifests/gitops-primer.clusterserviceversion.yaml#L32) consider something like:
```
       kind: Export
       name: exports.primer.gitops.io
       version: v1alpha1
-  description: export and normalize kubernetes based yaml's for GitOps
+  description: Export and normalize Kubernetes YAML files for GitOps
   displayName: gitops-primer
   icon:
```

**Review by rayfordj — CHANGES_REQUESTED** [review]
Address suggestions in my other comments and I think we should be good to merge.

**Review by jmontleon — APPROVED** [review]
ACK

**Comment by jmontleon** [comment]
I think this looks good. Either here or in a separate PR we'll want to add a category as @rayfordj pointed out, as it also appears to be a requirement to have a valid one for the Community Operators repo.

**Comment by cooktheryan** [comment]
@rayfordj I think I got all of the items. Let me know if I missed anything

**Comment by jmontleon** [comment]
LGTM

**Review by rayfordj — APPROVED** [review]
/lgtm

**Pull request merged**
